HEART_RATE_PREDICTOR:
  algorithm: "random_forest"  
  n_estimators: 500
  max_depth: 15
  min_samples_split: 20
  min_samples_leaf: 10
  max_features: "log2"
  random_state: 42
  
ANOMALY_DETECTOR:
  algorithm: "isolation_forest"
  n_estimators: 200       
  max_samples: 120000       
  contamination: 0.035    
  max_features: 1.0        
  random_state: 42         
  n_jobs: -1               
