HEART_RATE_PREDICTOR:
  algorithm: "random_forest"  
  n_estimators: 100
  max_depth: 10
  random_state: 42
  

ANOMALY_DETECTOR:
  algorithm: "isolation_forest"  
  contamination: 0.1
  n_estimators: 100
  random_state: 42