HEART_RATE_PREDICTOR:
  algorithm: "random_forest"  
  n_estimators: 100
  max_depth: 10
  random_state: 42
  
ANOMALY_DETECTOR:
  algorithm: "isolation_forest"
  n_estimators: 200       
  max_samples: 120000       
  contamination: 0.035    
  max_features: 1.0        
  random_state: 42         
  n_jobs: -1               
