artifacts_root: artifacts

data_generation:
  root_dir: artifacts/data_generation
  local_data_files:
    readings: artifacts/data_generation/data/Health_Dataset_readings.csv
    users: artifacts/data_generation/data/Health_Dataset_users.csv



data_transformation:
  root_dir: artifacts/data_transformation
  data_path:
    readings: artifacts/data_generation/data/Health_Dataset_readings.csv
    users: artifacts/data_generation/data/Health_Dataset_users.csv


model_trainer:
  root_dir: artifacts/model_trainer
  data_path:
    train_heart_rate: artifacts/data_transformation/train_heart_rate.csv
    test_heart_rate: artifacts/data_transformation/test_heart_rate.csv
    train_is_anomaly: artifacts/data_transformation/train_is_anomaly.csv
    test_is_anomaly: artifacts/data_transformation/test_is_anomaly.csv
  model_name: 
    heart_rate_predictor: Heart_Rate_Predictor_model.joblib
    anomaly_detector: Anomaly_Detector_model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path:
    heart_rate_predictor: artifacts/data_transformation/test_heart_rate.csv
    anomaly_detector: artifacts/data_transformation/test_is_anomaly.csv
  model_path:
    heart_rate_predictor: artifacts/model_trainer/Heart_Rate_Predictor_model.joblib
    anomaly_detector: artifacts/model_trainer/Anomaly_Detector_model.joblib
  report_path:
    heart_rate_predictor: artifacts/model_evaluation/heart_rate_report.yaml
    anomaly_detector: artifacts/model_evaluation/anomaly_report.yaml
  target_columns:
    heart_rate_predictor: heart_rate
    anomaly_detector: is_anomaly


