artifacts_root: artifacts

data_generation:
  root_dir: artifacts/data_generation
  local_data_files:
    readings: artifacts/data_generation/data/Health_Dataset_readings.csv
    users: artifacts/data_generation/data/Health_Dataset_users.csv



data_transformation:
  root_dir: artifacts/data_transformation
  data_path:
    readings: artifacts/data_generation/data/Health_Dataset_readings.csv
    users: artifacts/data_generation/data/Health_Dataset_users.csv




